# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestDemo
    pod 'Alamofire', '4.4.0'
    pod 'SDWebImage'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'IQKeyboardManagerSwift'
    pod 'CropViewController'
    pod 'DKImagePickerController'

	
	

  target 'TestDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestDemoUITests' do
    # Pods for testing
  end

end
